// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getConfig = `-- name: GetConfig :one

SELECT watch_dir, organized_dir, archive_dir, expose_service, port, compression_enabled, archive_days, max_retention_days, log_level FROM config LIMIT 1
`

// Config queries
func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i Config
	err := row.Scan(
		&i.WatchDir,
		&i.OrganizedDir,
		&i.ArchiveDir,
		&i.ExposeService,
		&i.Port,
		&i.CompressionEnabled,
		&i.ArchiveDays,
		&i.MaxRetentionDays,
		&i.LogLevel,
	)
	return i, err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE config
SET watch_dir = ?,
organized_dir = ?,
archive_dir = ?,
expose_service = ?,
port = ?,
compression_enabled = ?,
archive_days = ?,
max_retention_days = ?,
log_level = ?
`

type UpdateConfigParams struct {
	WatchDir           sql.NullString
	OrganizedDir       sql.NullString
	ArchiveDir         sql.NullString
	ExposeService      sql.NullBool
	Port               sql.NullInt64
	CompressionEnabled sql.NullBool
	ArchiveDays        sql.NullInt64
	MaxRetentionDays   sql.NullInt64
	LogLevel           sql.NullString
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.WatchDir,
		arg.OrganizedDir,
		arg.ArchiveDir,
		arg.ExposeService,
		arg.Port,
		arg.CompressionEnabled,
		arg.ArchiveDays,
		arg.MaxRetentionDays,
		arg.LogLevel,
	)
	return err
}
