// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletes.sql

package sqlc

import (
	"context"
)

const deleteCapture = `-- name: DeleteCapture :exec

DELETE FROM captures
WHERE id = ?
`

// Delete queries
func (q *Queries) DeleteCapture(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCapture, id)
	return err
}
