// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inserts.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const insertCapture = `-- name: InsertCapture :one
INSERT INTO captures (
    hostname,
    scenario,
    capture_datetime,
    file_path,
    file_size,
    compressed,
    archived,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertCaptureParams struct {
	Hostname        string
	Scenario        string
	CaptureDatetime time.Time
	FilePath        string
	FileSize        int64
	Compressed      sql.NullBool
	Archived        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCapture,
		arg.Hostname,
		arg.Scenario,
		arg.CaptureDatetime,
		arg.FilePath,
		arg.FileSize,
		arg.Compressed,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCaptureStats = `-- name: InsertCaptureStats :exec

INSERT INTO capture_stats (
    capture_id,
    packet_count,
    protocol_distribution,
    top_src_ips,
    top_dst_ips,
    top_tcp_src_ports,
    top_tcp_dst_ports,
    top_udp_src_ports,
    top_udp_dst_ports,
    packet_rate,
    avg_packet_size,
    duration_seconds,
    first_packet_time,
    last_packet_time
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertCaptureStatsParams struct {
	CaptureID            int64
	PacketCount          sql.NullInt64
	ProtocolDistribution sql.NullString
	TopSrcIps            sql.NullString
	TopDstIps            sql.NullString
	TopTcpSrcPorts       sql.NullString
	TopTcpDstPorts       sql.NullString
	TopUdpSrcPorts       sql.NullString
	TopUdpDstPorts       sql.NullString
	PacketRate           sql.NullFloat64
	AvgPacketSize        sql.NullFloat64
	DurationSeconds      sql.NullInt64
	FirstPacketTime      sql.NullTime
	LastPacketTime       sql.NullTime
}

// Insert queries
func (q *Queries) InsertCaptureStats(ctx context.Context, arg InsertCaptureStatsParams) error {
	_, err := q.db.ExecContext(ctx, insertCaptureStats,
		arg.CaptureID,
		arg.PacketCount,
		arg.ProtocolDistribution,
		arg.TopSrcIps,
		arg.TopDstIps,
		arg.TopTcpSrcPorts,
		arg.TopTcpDstPorts,
		arg.TopUdpSrcPorts,
		arg.TopUdpDstPorts,
		arg.PacketRate,
		arg.AvgPacketSize,
		arg.DurationSeconds,
		arg.FirstPacketTime,
		arg.LastPacketTime,
	)
	return err
}
