// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Capture struct {
	ID              int64
	Hostname        string
	Scenario        string
	CaptureDatetime time.Time
	FilePath        string
	FileSize        int64
	Compressed      sql.NullBool
	Archived        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type CaptureStat struct {
	ID                   int64
	PacketCount          sql.NullInt64
	CaptureID            int64
	ProtocolDistribution sql.NullString
	TopSrcIps            sql.NullString
	TopDstIps            sql.NullString
	TopTcpSrcPorts       sql.NullString
	TopTcpDstPorts       sql.NullString
	TopUdpSrcPorts       sql.NullString
	TopUdpDstPorts       sql.NullString
	PacketRate           sql.NullFloat64
	AvgPacketSize        sql.NullFloat64
	DurationSeconds      sql.NullInt64
	FirstPacketTime      sql.NullTime
	LastPacketTime       sql.NullTime
	CreatedAt            sql.NullTime
}

type Config struct {
	WatchDir           sql.NullString
	OrganizedDir       sql.NullString
	ArchiveDir         sql.NullString
	CompressionEnabled sql.NullBool
	ArchiveDays        sql.NullInt64
	MaxRetentionDays   sql.NullInt64
	LogLevel           sql.NullString
}
