// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getConfig = `-- name: GetConfig :one
SELECT watch_dir, organized_dir, archive_dir, compression_enabled, archive_days, max_retention_days, cleanup_interval_hours, batch_size, log_level, updated_at FROM config LIMIT 1
`

func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i Config
	err := row.Scan(
		&i.WatchDir,
		&i.OrganizedDir,
		&i.ArchiveDir,
		&i.CompressionEnabled,
		&i.ArchiveDays,
		&i.MaxRetentionDays,
		&i.CleanupIntervalHours,
		&i.BatchSize,
		&i.LogLevel,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCapture = `-- name: InsertCapture :one
INSERT INTO captures (
    hostname,
    scenario,
    capture_datetime,
    file_path,
    file_size,
    compressed,
    archived,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertCaptureParams struct {
	Hostname        string
	Scenario        string
	CaptureDatetime time.Time
	FilePath        string
	FileSize        int64
	Compressed      sql.NullBool
	Archived        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCapture,
		arg.Hostname,
		arg.Scenario,
		arg.CaptureDatetime,
		arg.FilePath,
		arg.FileSize,
		arg.Compressed,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCaptureStats = `-- name: InsertCaptureStats :exec
INSERT INTO capture_stats (
    capture_id,
    packet_count,
    protocol_distribution,
    top_src_ips,
    top_dst_ips,
    top_ports,
    packet_rate,
    avg_packet_size,
    tls_versions,
    dns_queries,
    duration_seconds,
    first_packet_time,
    last_packet_time
    ) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    )
`

type InsertCaptureStatsParams struct {
	CaptureID            int64
	PacketCount          sql.NullInt64
	ProtocolDistribution sql.NullString
	TopSrcIps            sql.NullString
	TopDstIps            sql.NullString
	TopPorts             sql.NullString
	PacketRate           sql.NullFloat64
	AvgPacketSize        sql.NullFloat64
	TlsVersions          sql.NullString
	DnsQueries           sql.NullInt64
	DurationSeconds      sql.NullInt64
	FirstPacketTime      sql.NullTime
	LastPacketTime       sql.NullTime
}

func (q *Queries) InsertCaptureStats(ctx context.Context, arg InsertCaptureStatsParams) error {
	_, err := q.db.ExecContext(ctx, insertCaptureStats,
		arg.CaptureID,
		arg.PacketCount,
		arg.ProtocolDistribution,
		arg.TopSrcIps,
		arg.TopDstIps,
		arg.TopPorts,
		arg.PacketRate,
		arg.AvgPacketSize,
		arg.TlsVersions,
		arg.DnsQueries,
		arg.DurationSeconds,
		arg.FirstPacketTime,
		arg.LastPacketTime,
	)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE config
SET watch_dir = ?,
organized_dir = ?,
archive_dir = ?,
compression_enabled = ?,
archive_days = ?,
max_retention_days = ?,
cleanup_interval_hours = ?,
batch_size = ?,
log_level = ?,
updated_at = current_timestamp
`

type UpdateConfigParams struct {
	WatchDir             sql.NullString
	OrganizedDir         sql.NullString
	ArchiveDir           sql.NullString
	CompressionEnabled   sql.NullBool
	ArchiveDays          sql.NullInt64
	MaxRetentionDays     sql.NullInt64
	CleanupIntervalHours sql.NullInt64
	BatchSize            sql.NullInt64
	LogLevel             sql.NullString
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.WatchDir,
		arg.OrganizedDir,
		arg.ArchiveDir,
		arg.CompressionEnabled,
		arg.ArchiveDays,
		arg.MaxRetentionDays,
		arg.CleanupIntervalHours,
		arg.BatchSize,
		arg.LogLevel,
	)
	return err
}
