// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updates.sql

package sqlc

import (
	"context"
)

const markCaptureAsArchived = `-- name: MarkCaptureAsArchived :exec

UPDATE captures
SET archived = 1, updated_at = current_timestamp
WHERE id = ?
`

// Update queries
func (q *Queries) MarkCaptureAsArchived(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markCaptureAsArchived, id)
	return err
}

const markCaptureAsCompressed = `-- name: MarkCaptureAsCompressed :exec
UPDATE captures
SET compressed = 1, updated_at = current_timestamp
WHERE id = ?
`

func (q *Queries) MarkCaptureAsCompressed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markCaptureAsCompressed, id)
	return err
}

const updateFilePath = `-- name: UpdateFilePath :exec
UPDATE captures
SET file_path = ?, updated_at = current_timestamp
WHERE id = ?
`

type UpdateFilePathParams struct {
	FilePath string
	ID       int64
}

func (q *Queries) UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) error {
	_, err := q.db.ExecContext(ctx, updateFilePath, arg.FilePath, arg.ID)
	return err
}
